const colorArray = [
 'aqua', 'aquamarine', 
 'black', 'blue', 'blueviolet', 
 'brown', 'burlywood', 'cadetblue', 'chartreuse', 
 'chocolate', 'coral', 'cornflowerblue',
 'crimson', 'cyan', 'darkblue', 'darkcyan', 'darkgoldenrod',
  'darkgray', 'darkgrey', 'darkgreen', 'darkkhaki',
  'darkmagenta', 'darkolivegreen', 'darkorange', 'darkorchid',
   'darkred', 'darksalmon', 'darkseagreen', 'darkslateblue', 
   'darkslategray', 'darkslategrey', 'darkturquoise', 
   'darkviolet', 'deeppink', 'deepskyblue', 'dimgray', 'dimgrey',
    'dodgerblue', 'firebrick', 'forestgreen', 
    'fuchsia', 'gainsboro', 'gold', 'goldenrod', 
    'gray', 'grey', 'green', 'greenyellow',
    'hotpink', 'indianred', 'indigo', 'ivory', 'khaki', 
    'lavender', 'lavenderblush', 'lawngreen', 'lemonchiffon', 
    'lightblue', 'lightcoral', 'lightcyan', 
     'lightgray', 'lightgrey', 'lightgreen', 'lightpink', 'lightsalmon',
      'lightseagreen', 'lightskyblue', 'lightslategray', 'lightslategrey', 
      'lightsteelblue', 'lightyellow', 'lime', 'limegreen',
      'magenta', 'maroon', 'mediumaquamarine', 'mediumblue', 'mediumorchid', 
      'mediumpurple', 'mediumseagreen', 'mediumslateblue', 'mediumspringgreen',
       'mediumturquoise', 'mediumvioletred', 'midnightblue', 'mintcream', 'mistyrose', 
       'moccasin', 'navy', 'olive', 'olivedrab', 'orange',
        'orangered', 'orchid', 'palegoldenrod', 'palegreen', 'paleturquoise', 'palevioletred', 
        'papayawhip', 'peachpuff', 'peru', 'pink', 'plum', 'powderblue', 'purple', 'red', 
        'rosybrown', 'royalblue', 'saddlebrown', 'salmon', 'sandybrown', 'seagreen', 
        'seashell', 'sienna', 'silver', 'skyblue', 'slateblue', 'slategray', 'slategrey',
         'snow', 'springgreen', 'steelblue', 'tan', 'teal', 'thistle', 'tomato', 'turquoise', 
         'violet', 'wheat', 'yellow', 'yellowgreen'];

          
          export default colorArray